In [153]:
import numpy as np
import pandas as pd

In [154]:
out=np.array([0,0,1,0,1,1,0]) #sunny=0, cloudy=1
temp=np.array([0,1,1,1,0,0,0]) #cold=0, warm=1
rtn=np.array([0,1,0,0,0,1,1]) #indoor=0, outdoor= 1
cot=np.array([0,0,0,0,1,1,1]) #no=0, yes=1

In [155]:
out.size
temp.size
rtn.size
cot.size

7

## X_yes 

In [156]:
c1=cot[4:7]
print(c1)
c1.size
x1=np.where(c1==1)
print(x1)
x1_size=len(x1[0])
print(x1_size)


[1 1 1]
(array([0, 1, 2], dtype=int64),)
3


In [157]:
o1 = out[4:7]
print(o1)
o1.size
a1 = np.where(o1 == 1)
print(a1)
a1_size=len(a[0])
print(a1_size)

[1 1 0]
(array([0, 1], dtype=int64),)
2


In [158]:
t1 = temp[4:7]
print(t1)
t1.size
b1 = np.where(t1 == 1)
print(b1)
b1_size=len(b1[0])
print(b1_size)

[0 0 0]
(array([], dtype=int64),)
0


In [159]:
r1 = rtn[4:7]
print(r1)
r1.size
d1 = np.where(r1 == 1)
print(d1)
d1_size=len(d1[0])
print(d1_size)

[0 1 1]
(array([1, 2], dtype=int64),)
2


In [160]:
X_yes=((a1_size/o1.size)*(b1_size/t1.size)*(d1_size/r1.size)*(x1_size/cot.size))/((o1.size/rtn.size)*(t1.size/temp.size)*(r1.size/rtn.size))

print(X_yes)

0.0


## X_no

In [161]:
c0=cot[0:4]
print(c0)
c0.size
x0=np.where(c0==0)
print(x0)
x0_size=len(x0[0])
print(x0_size)

[0 0 0 0]
(array([0, 1, 2, 3], dtype=int64),)
4


In [162]:
o0 = out[0:4]
print(o0)
print(o0.size)

a0 = np.where(o0 == 0)
print(a0)
a0_size=len(a0[0])
print(a0_size)

[0 0 1 0]
4
(array([0, 1, 3], dtype=int64),)
3


In [163]:
t0 = temp[0:4]
print(t0)
print(t0.size)

b0 = np.where(t0 == 0)
print(b0)
b0_size=len(b0[0])
print(b0_size)

[0 1 1 1]
4
(array([0], dtype=int64),)
1


In [164]:
r0 = rtn[0:4]
print(r0)
print(r0.size)

d0 = np.where(r0 == 0)
print(d0)
d0_size=len(d0[0])
print(d0_size)

[0 1 0 0]
4
(array([0, 2, 3], dtype=int64),)
3


In [165]:
X_no=((a0_size/o0.size)*(b0_size/t0.size)*(d0_size/r0.size)*(x0_size/cot.size))/((o0.size/rtn.size)*(t0.size/temp.size)*(r0.size/rtn.size))

print(X_no)

0.43066406250000006
