###         Mohammad Shakirul Islam
###               ID: 151-15-311

In [280]:
import numpy as np

In [281]:
out=np.array([0,0,1,0,1,1,0]) #sunny=0, cloudy=1
temp=np.array([0,1,1,1,0,0,0]) #cold=0, warm=1
rtn=np.array([0,1,0,0,0,1,1]) #indoor=0, outdoor= 1
cot=np.array([0,0,0,0,1,1,1]) #no=0, yes=1

In [282]:
print('Outlook:',out.size,'| Temp:',temp.size ,'| Routine:',rtn.size,'| Coat:',cot.size)
#arr.size = len

Outlook: 7 | Temp: 7 | Routine: 7 | Coat: 7


##                                               P( C =yes | x )

In [283]:
c11 = np.transpose(np.nonzero(cot)) 
print(c11)

[[4]
 [5]
 [6]]


In [284]:
o1=out[4:]
t1=temp[4:]
r1=rtn[4:]

In [285]:
o11 =np.argwhere(o1==1) #print(o11)
#len(o11)

t11 =np.argwhere(t1==1)
#print(t11)
#len(t11)

r11 =np.argwhere(r1==1)
#print(r11)
o111 = np.argwhere(out==1)
t111 = np.argwhere(temp==1)
r111 = np.argwhere(rtn==1)
len(r111)

3

In [286]:
C_yes = ((o11.size/o1.size)*(t11.size/t1.size)*(r11.size/r1.size)*(c11.size/cot.size)) / ((o111.size/out.size)*(t111.size/temp.size)*(r111.size/rtn.size))
print("P( C =yes | x ) = ",C_yes)

P( C =yes | x ) =  0.0


##                                               P( C =no | x )

In [287]:
c22 = np.argwhere(cot == 0)
print(c22)

[[0]
 [1]
 [2]
 [3]]


In [288]:
o2=out[:4]
print(o2)

[0 0 1 0]


In [289]:
t2=temp[:4]
print(t2)

[0 1 1 1]


In [290]:
r2=rtn[:4]
print(r2)

[0 1 0 0]


In [291]:
o22 =np.argwhere(o2==1)
#len(o11)

t22 =np.argwhere(t2==1)
#print(t11)
#len(t11)

r22 =np.argwhere(r2==1)
#print(r11)
o222 = np.argwhere(out==1)
t222 = np.argwhere(temp==1)
r222 = np.argwhere(rtn==1)
#len(r222)

In [292]:
t22.size

3

In [293]:
C_no = ((o22.size/o2.size)*(t22.size/t2.size)*(r22.size/r2.size)*(c22.size/cot.size))/((o222.size/out.size)*(t222.size/temp.size)*(r222.size/rtn.size))
print("P( C = no | x )  = ",C_no)

P( C = no | x )  =  0.3402777777777778


In [294]:
if(C_no>C_yes):
    print ("Wear coat = no")
else:
    print("Wear coat = yes")

Wear coat = no


problem: https://classroom.google.com/u/1/c/MTEyMzc3MzE1MTda